### ISSUE TITLE
>> Fatal error in language file: Sentences "51" doesn't exists!

### ISSUE THREAD

**Issue by lineargraph** [Triploit-org/secundo-pm#3]
In a clean install (just clone'd/cmake'd/make'd) `sudo ./secpm` exits with the error message `>> Fatal error in language file: Sentences "51" doesn't exists!`

**Comment by piepert** [comment]
Pull the new Version 0.1.7.0, build the project and run `sudo ./secpm lang pkg/en.yml`, or `pkg/de.yml` for german. This will update the language file. After that, the error shouldn't show up again.

You can set the language in the config `/usr/share/secundo/conf/config.yml`, or run `sudo ./secpm config` and it'll open it with vi.
The option `langcfg` sets the language. All language files are in `/usr/share/secundo/lang`. The option `editor` sets the editor, that will open the config if you run `sudo ./secpm config`. I prefer nano or vim.

**Comment by piepert** [comment]
Okay, those errors won't show up again in version 0.1.7.1. I'm currently working on it. Hope no one in the future will get the same error :)
